### ISSUE TITLE
Missing symbols - Table of Symbols

### ISSUE THREAD

**Issue by peter-michalski** [sorainsm/library-of-lighting-models#11]
The following symbols are missing from the table of symbols:

DD1: P and Q
DD3,4,5,7: I think all of the I (with subscripts) should have their own placement in the table
DD5: k and v 
DD7,8: p

Table 1: R (real numbers) & Z

IM1: p
IM2: k
IM3: v
IM4: h

**Comment by sorainsm** [comment]
@peter-michalski thanks for the detailed list! It made this easier to resolve. This has been resolved in 4de121196dbf91a2a56da1883f716e26c560cdf3

@smiths is there a way to capture that all capital letters (i.e. P and Q) are of the same type (i.e. n-dimensional vectors).

**Comment by smiths** [comment]
@sorainsm, if you have typographic conventions, like capital letters are n-dimensional vectors, you can define that in the Reference Material section of the document.  You could add a section for typographic conventions (or similar wording).  

I'll close this issue because the work has been done, and because the question has been answered.  @sorainsm, if you want to add a typographic conventions section, you could create a separate issue for that (possibly with a reference to this issue.)
