### ISSUE TITLE
Question: Is this two data definition related?

### ISSUE THREAD

**Issue by sharyuwu** [sorainsm/library-of-lighting-models#15]
@smiths 
Question: Are DD1 and DD2 related?

Based on the description of DD2, it seems like (P x Q)[DD2] is also a unit of P．Q [DD1]. If this is true, then should DD2 and DD1 refer to each other?
Or maybe put DD1 to General Definition because, in T1 and GD1, it looks like it refines DD1.

Like refine P ． Q to Li．N

![image](https://user-images.githubusercontent.com/55363335/67138339-a816ab80-f20f-11e9-9b07-9d52dfb74ee3.png)

![image](https://user-images.githubusercontent.com/55363335/67138341-b238aa00-f20f-11e9-9e29-bee46bb4d907.png)

**Comment by sorainsm** [comment]
DD1 and DD2 are related (as they're both Vector calculus).

From my understanding of DD they are concepts that are used in the refinement of IMs and TMs. In this case, dot products and cross products are used extensively in calculating lighting for graphics. As such I thought they would be appropriate here as they are definitions that are going to be used throughout the problem and so it is important that people reading this document know what they are.

I'm going to leave them as separate DDs because they are different functions that do different things and are used in different places (sometimes together).
