### ISSUE TITLE
Question: Does DD7 is refereed by other models?

### ISSUE THREAD

**Issue by sharyuwu** [sorainsm/library-of-lighting-models#20]
@sorainsm 
The first question is, does DD7 is refereed by other models?
Based on this document, DD7 is only referred by AB1 and AB2, but not other models. Therefore, if this data does not drive other models, then this data seems redundant.

The second question is, what is the meaning of I(p0)?
Based on my understanding, it means the intensity from the point p0. Please correct me if I wrong. Therefore, it leads to my next question. Is there any equation able to calculate the intensity from the point p0, or is it a given value?

![image](https://user-images.githubusercontent.com/55363335/67149915-30806500-f27f-11e9-8ca7-e49193450071.png)

**Comment by sorainsm** [comment]
DD7 is actually one of the most important functions here as it allows for the calculations of all the IMs.
It was an oversight on my part missing all the things it is referenced by! 

I(p0) os the intensity of light at point p0 - specifically p0 is the origin of the light source, so I(p0) is the maximum intensity of the light. This will be a given value from the light source.

At the time I was unsure how to write this information since it's something that's going to be an attribute of the light source (and I was trying to wrap my head around abstracting it from the data structure of the light source).

I've fixed the reference issues and attempted to clarify I(p0) in cb95e52e54dcfd0b1df559731131bd8280acd53e - please review the changes and let me know if they address this concern.
