### ISSUE TITLE
System VnV Review: Are Ease of Installation Test Cases Appropriate?

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#23]
Hi Zhi, my System VnV is ready to review (71f977d04f1b2d24b20706e1098ab039910c9426)

Could you please take a look at my Ease of Installation test cases (5.2.1 Usability Testing - Ease of Installation) to see whether the wording there is appropriate?

The intention of the system is that it will be a plug-in to the Unity development environment, as such I have made the decision that "uninstalling" is not an option since (by nature of Unity) the plugin scripts would be installed on a project by project basis. Does this make sense? Do you think I should include an "uninstall" option and test case?

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Sasha, 

I think the Ease of Installation test cases are good! But I don't see why you have current and previous versions. Installation of any versions should be similar I guess? 

And for the "uninstall", I don't think it's important since no developers are expecting users to uninstall their software lol.

**Comment by smiths** [comment]
@best-zhang-zhi, I actually like the uninstall version.  It is frustrating at times to remove software because it has silently installed files all over my machine.  Uninstall is a useful test.

Since @best-zhang-zhi has addressed the original question, we can close this issue.
