### ISSUE TITLE
Commonality Analysis: Assumption Check

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#3]
Is this division of assumptions (by binding time, and then general assumptions) appropriate for this work?

Do general assumptions even exist, or should they all exist at a specific binding time (e.g. coordinate system is a scope decision because we're not considering others).

_NOTE: These sections are still a work in progress._

![image](https://user-images.githubusercontent.com/11723492/66178716-4dd4f280-e634-11e9-8158-9ce6fff2105f.png)
![image](https://user-images.githubusercontent.com/11723492/66178744-61805900-e634-11e9-8d95-bdc93ea2cc90.png)

**Comment by smiths** [comment]
@sorainsm, I like your proposed classifications.  This seems like a good idea.  I'll think about adding it to the template for the future.  :smile:  I think all of the assumptions should have an associated binding time, although for a family of families, the binding time could be variable.  That is the binding time itself could be a variability that distinguishes families.  Maybe your unclassified assumptions could be in the category of "build time or run time"?

Your run time bindings are really just inputs.  I think rather than list them as assumptions, I would suggest listing them as inputs.

**Comment by sorainsm** [comment]
I agree that the "unclassified assumptions" should be elsewhere. In re-reading I ended up moving them around (A1 to build time as it was a build time decision to use Cartesian coordinates rather than other methods; A2 and A3 moved to input).

I've removed the previous run-time bindings, and instead have captured this information as input variabilities (see commit 22edeee19c834a57847365d81f8560206fa81bbb). I'm closing this issue.

![image](https://user-images.githubusercontent.com/11723492/66449698-067ba700-ea24-11e9-987e-19f4c7d9a9a6.png)
